#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

# init-bottom runs late, right before the real root takes over -- the
# same point dracut's pre-pivot hook occupies.
grep -q ' /sys/fs/bpf ' /proc/mounts || mount -t bpf bpf /sys/fs/bpf

SRCDIR="/opt/bpf-lsm-progs"	# must match the SRCDIR in hooks/bpf-lsm
BPFTARGET="bpfel"	# must match the BPFTARGET in hooks/bpf-lsm

for p in setuid_restrict userns_restrict; do
	/sbin/bpftool prog loadall "$SRCDIR/$p.$BPFTARGET.o" "/sys/fs/bpf/$p" autoattach
done
