#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
### BEGIN INIT INFO
# Provides:          bpf-tracepipe
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Forward BPF trace_pipe output to syslog
### END INIT INFO

NAME=bpf-tracepipe
PIDFILE=/run/$NAME.pid

case "$1" in
	start)
		start-stop-daemon --start --background --make-pidfile --pidfile "$PIDFILE" \
			--exec /bin/sh -- -c 'mountpoint -q /sys/kernel/tracing || mount -t tracefs tracefs /sys/kernel/tracing; exec cat /sys/kernel/tracing/trace_pipe | logger -t bpf'
		;;
	stop)
		start-stop-daemon --stop --pidfile "$PIDFILE" --remove-pidfile
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	status)
		start-stop-daemon --status --pidfile "$PIDFILE"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}" >&2
		exit 1
		;;
esac
